out_dir: results
metric_best: mae
metric_agg: argmin
tensorboard_each_run: False  # Log to Tensorboard each run
#accelerator: "cuda:3"
#device: "cuda:3"
accelerator: "cuda:3"
device: "cuda:3"
mlflow:
  use: False
  project: Exp
  name: mydata-GRIT-RRWP
wandb:
  use: False
  project: mydata
dataset:
  format: PyG-mydatacomplex
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 2
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 2
  edge_encoder_bn: False
  add_virtual_node_edge: False
  subgraph: False
  remove_h: False
train:
  mode: qm9_unconditional
  batch_size: 64
  eval_batch_size: 2048
  eval_period: 1
  start_eval_epoch: -1
  enable_ckpt: True  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: False  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
  ckpt_clean: False # Delete old ckpt each time.
  ckpt_period: 25
  ensemble_repeat: 1
  ensemble_mode: none
  pretrain:
    mask_node_prob: 0.0
    mask_edge_prob: 0.0
    mask_label_prob: 0.0
    recon: all
    original_task: False
    input_target: False
    node_factor: 1.0
    edge_factor: 1.0
    graph_factor: 0.0
model:
  type: LatentDiffusion
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
  diffusion_model: DenoisingHOGNN
posenc_RRWP:
  enable: True
  ksteps: 16
encoder:
  model_type: HOGNNEncoder
  in_dim: 48
  prefix_dim: 96
  posenc_in_dim: 16
  posenc_in_dim_edge: 16
  posenc_dim: 48
  pe_raw_norm: None
  hid_dim: 96
  out_dim: 32
  use_time: False
  temb_dim: 0
  num_heads: 4
  num_layers: 5
  dropout: 0.2
  attn_dropout: 0.5
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
    fwl: False
    signed_sqrt: True
    score_act: True
    deg_scaler: False
    attn_product: mul
    attn_reweight: False
    edge_reweight: False
  mpnn:
    enable: True
    act: 'relu'
    dropout: 0.2
    edge_enhance: True
    project_edge: True
  residual: True
  layer_norm: False
  batch_norm: True
  act: 'relu'
  norm_e: True
  O_e: True
  ff_e: True
  update_e: True
  force_undirected: True
  pool: mean
  pool_edge: True
  pool_vn: False
  post_pool: False
  final_norm: True
  prefix_type: add_all
  label_embed_type: add_all
  num_task: 1
  task_type: regression
  # num_classes: only for classification
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 2 # actually 21 in Zinc-12k, 28 in Zinc-full
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 2
  edge_encoder_bn: False
  add_virtual_node_edge: False
  subgnn:
    type: 'NGNN'
    num_layers: 6
    c_hid: 4
hognn:
  in_dim: 32  # should be the same as encoder.out_dim
  hid_dim: 256
  out_dim: 32
  num_layers: 6
  act: 'relu'
  type: 'NGNN'
  dropout: 0.2
  force_undirected: True
  pool: mean
  pool_edge: True
  pool_vn: False
  post_pool: False
  layer_norm: False
  batch_norm: True
  bn_momentum: 0.1
  bn_no_runner: False
  norm_e: True
  final_norm: True
dt:
  in_dim: 32  # should be the same as encoder.out_dim
  hid_dim: 256
  out_dim: 32
  use_time: True
  temb_dim: 128
  cond_dim: 16
  num_heads: 16
  num_layers: 8
  self_attn: True
  dropout: 0.05
  attn_dropout: 0.1
  residual: True
  layer_norm: False
  batch_norm: True
  act: 'relu'
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
    fwl: False
    signed_sqrt: True
    score_act: True
    deg_scaler: False
    attn_product: mul
    attn_reweight: False
    edge_reweight: False
  norm_e: True
  O_e: True
  ff_e: True
  ff_e_ca: True
  ff_e_sa: True
  update_e: True
  force_undirected: True
  pool: mean
  pool_edge: True
  pool_vn: False
  post_pool: False
  final_norm: True
  condition_list: ['unconditional']
diffusion:
  conditioning_key: crossattn
  hid_dim: 32  # should be the same as dt.in_dim
  parameterization: "x0"
  cond_stage_key: unconditional
  first_stage_config: results/ngnn-encoder_100_complex_old/3/ckpt/1999.ckpt
  cond_stage_config: '__is_unconditional__'
  node_factor: 1.0
  edge_factor: 1.0
  graph_factor: 0.0
  recon_factor: 0.0
  task_factor: 0.0
  force_undirected: True
gt:
  layer_type: GritTransformer
  layers: 10
  n_heads: 8
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  layer_norm: False
  batch_norm: True
#  bn_momentum: 0.01
  update_e: True
  attn_dropout: 0.2
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
    fwl: False
gnn: # decoder --> san_graph = MLP + pooling
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 1e-4
  max_epoch: 2000
  num_warmup_epochs: 50
  scheduler: cosine_with_warmup
  min_lr: 1e-6